spring:
  application:
    name: Student Test Application
  output:
    ansi:
      enabled: always
banner:
  location: 'classpath:banner.txt'
test:
  locale: ru_RU
  separator: ','
  name: 'test_${test.locale}.csv'
  pass: 50